language: python

python:
      - "2.7"

install:
       - pip install -r requirements.txt
       - pip install coveralls

before_script:
  - psql -c 'create database test_hello_books_db;' -U postgres

script: nosetests --with-coverage

after_success:
       - coveralls

