FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# HelloAPI

HelloAPI is a simple API that allows consumers to view, borrow and return books.

## endpoints [/endpoints]

### Registration [POST]

+ Request (form-data)

        {
        "username": "john doe",
        "email": "johndoeemail@gmail.com",
        "password": "very-very-secret"
        }
        
+ Response 201 (application/json)

        {
        "message": "you have successfully registered"
        }
        
### Login [POST]

+ Request (form-data)

        {
        "email": "johndoeemail@gmail.com",
        "password": "very-very-secret"
        }
        
+ Response 201 (application/json)

        {
        "message": "you have successfully logged in"
        }

### get all books [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Book [POST]

The admin uses this endpoint to add new books to the library.

+ Request (application/json)

        {
            "title": "the lost sheep",
            "author": "Jason Pontius",
            "category": "children book",
            "url": "https:///unsplash/pontius"
        }

+ Response 201 (application/json)

    + Headers


                'content-type': 'application/json',
                'Authorization': 'Bearer {}'.format(access_token)

    + Body

            {
            "title": "the lost sheep",
            "author": "Jason Pontius",
            "category": "children book",
            "url": "https:///unsplash/pontius"
            }
            
### Edit a Book [PUT]

The admin uses this endpoint to edit a book in the library.

+ Request (application/json)

        {
            "title": "the lost sheep and the silly goat",
            "author": "Jason Pontius pilate",
            "category": "children book",
            "url": "https:///unsplash/pontius"
        }

+ Response 201 (application/json)

    + Headers
    
        
            'content-type': 'application/json',
            'Authorization': 'Bearer {}'.format(access_token)


    + Body

            {
            "title": "the lost sheep and the silly goat",
            "author": "Jason Pontius pilate",
            "category": "children book",
            "url": "https:///unsplash/pontius"
            }
            
### Delete a Book [DELETE]

The admin uses this endpoint to remove a book from the library.

+ Request (application/json)

        {
            "title": "the lost sheep and the silly goat",
            "author": "Jason Pontius pilate",
            "category": "children book",
            "url": "https:///unsplash/pontius"
        }

+ Response 201 (application/json)

    + Headers
    
        
            'content-type': 'application/json',
            'Authorization': 'Bearer {}'.format(access_token)


    + Body

            {
             "message": "book successfully deleted"
            }